### ISSUE TITLE
[UNBLOCK]

### ISSUE THREAD

**Issue by ghost** [tiuxo/hosts#15]
**Domains to be removed:**
- ad.dmm.com

**Reason for removal:**
Visit https://www.dmm.co.jp/0-000

0 is the affiliate code.

After redirecting to ip.affiliate.dmm.com, you will be redirected to ad.dmm.com

I want you to remove this domain if possible.

**Comment by brianclemens** [comment]
Some banner ads are also served from that domain, and they are of the particularly annoying "giant porn banner" variety. As such, I will not be removing that domain from the list.
