### ISSUE TITLE
Google APIs (fonts)

### ISSUE THREAD

**Issue by StevenBlack** [tiuxo/hosts#2]
Hi Brian, have you seen my [issue 967](https://github.com/StevenBlack/hosts/issues/967)?

Cheers!

**Comment by brianclemens** [comment]
Sorry, didn't see the ping there.  Fixed.

**Comment by StevenBlack** [comment]
Awesome!  Thanks!

**Comment by StevenBlack** [comment]
Hi again, Brian.

It looks like we need `gstaticadssl.l.google.com` unblocked too.

See subsequent comments in my [issue 967](https://github.com/StevenBlack/hosts/issues/967).

Thanks.
