### ISSUE TITLE
[UNBLOCK]

### ISSUE THREAD

**Issue by W1ndst0rm** [tiuxo/hosts#24]
**Domains to be removed:**
animate.adobe.com

**Reason for removal:**
These sites do not contain content relevant to the blocklist they are on. This is Adobe's CDN that contains the runtimes its JavaScript animation libraries. https://www.adobe.com/devnet-docs/edgeanimate/api/current/index.html#CDN-Hosting

**Comment by brianclemens** [comment]
Removed in 1831405
