### ISSUE TITLE
[UNBLOCK]

### ISSUE THREAD

**Issue by jdck** [tiuxo/hosts#26]
**Domains to be removed:**
- cint.com

**Reason for removal:**
See [AdAway issue #105](https://github.com/AdAway/adaway.github.io/issues/105).
> This prevents me from filling out the questionnaire to https://sw.ktrmr.com/ . This is a survey questionnaire platform and its matcher, not an ad.

**Screenshot:**
![image](https://user-images.githubusercontent.com/16664309/101195033-c94b8d00-3699-11eb-9496-ee81b23afcc3.png)

**Comment by spirillen** [comment]
No it's SpyWare / TrackWare :unamused:

**Comment by brianclemens** [comment]
Doesn't look like it actually. Removed.
