### ISSUE TITLE
[UNBLOCK] crashlytics.com

### ISSUE THREAD

**Issue by aravindvnair99** [tiuxo/hosts#27]
[Firebase Crashlytics](https://firebase.google.com/products/crashlytics) is a lightweight, realtime crash reporter that helps developers track, prioritize, and fix stability issues that erode app quality. Crashlytics saves developers troubleshooting time by intelligently grouping crashes and highlighting the circumstances that lead up to them.

I don't think Crashlytics should be blocked. It's used in various apps and is useful for a lot of developers.

**Comment by brianclemens** [comment]
"Good" tracking is still tracking.
