### ISSUE TITLE
bufferapp.com

### ISSUE THREAD

**Issue by dnmTX** [tiuxo/hosts#3]
@brianclemens  new issue arrived in [@StevenBlack's repo](https://github.com/StevenBlack/hosts/issues/977),not sure that you saw the ping.
I checked it and it's a legit app so if you don't mind whitelist it on your end. Thank you 👍

**Comment by brianclemens** [comment]
Got it, moved it to the social list.  Thanks!

**Comment by dnmTX** [comment]
Thanks @brianclemens  👍
