### ISSUE TITLE
narvar.com is for physical order tracking

### ISSUE THREAD

**Issue by lightswitch05** [tiuxo/hosts#4]
Narvar.com is used for physical order tracking, for example, if you order something from walmart.com or bedbathandbeyond.com and you get a link if an iframe that says something like 'where is my order?' - then the shipping details (tracking) that is shown is from narvar.com

Here is another example:

![image](https://user-images.githubusercontent.com/598803/58129555-fb94b700-7be7-11e9-867d-867e367bb642.png)

The button links to: `https://shutterfly.narvar.com/shutterfly/tracking/ups?tracking_numbers=<redacted>`

**Comment by brianclemens** [comment]
There are no narvar domains on any of these lists.  I've added it to the whitelist of troublesome domains, but the whitelist is not implemented anywhere yet.

**Comment by lightswitch05** [comment]
Oh wow, I must have grep’ed the wrong list. My apologies for wasting your time, but thank you for the prompt response
